# -*- coding: utf-8 -*-
"""Using_GeminiPro_For_TextExtraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1maIK5qDtb4CkIDDTSrrWTQBlU-bi_ZS5
"""

# Start of by installing this library
!pip install -q -U google-generativeai

# Importing the necessary packages
import pathlib
import textwrap

import google.generativeai as genai

# Used to securely store your API key
# Inside Userdata we can then store the api key
from google.colab import userdata

from IPython.display import display
from IPython.display import Markdown


def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

# Using genrated API key
import os
os.environ['GOOGLE_API_KEY']='AIzaSyCNJK-ueiRWHxkjpifqyPJaIE3ZehqPP4s'

genai.configure(api_key=os.environ['GOOGLE_API_KEY'])

import PIL.Image

img = PIL.Image.open('image-0079.png')
img

# Use the gemini-pro-vision model and pass the image to the model with generate_content.
model = genai.GenerativeModel('gemini-pro-vision')

# This part of the code, takes the image and gives out a response as what it can tell from the image it was fed
response = model.generate_content(img)

to_markdown(response.text)

# The output as a response
to_markdown(response.text)